In [1]:
import pandas as pd
import numpy as np
import scipy.stats as stats
import matplotlib as plt

In [2]:
data=pd.read_csv("Score.csv")
#data

In [3]:
col=np.array(data.columns)
col=np.delete(col,range(3))
#col

In [4]:
'''
maxScore1=[100 for i in range(36)]
maxScore2=[150,150,150,100,150,150,150,100,60,150,150,150,100,100,150,150,150,90,60]
maxScore=maxScore1+maxScore2
'''

'\nmaxScore1=[100 for i in range(36)]\nmaxScore2=[150,150,150,100,150,150,150,100,60,150,150,150,100,100,150,150,150,90,60]\nmaxScore=maxScore1+maxScore2\n'

In [5]:
transDataDict={}
for i in range(55):
    temp=(data[col[i]]-np.mean(data[col[i]]))/(np.max(data[col[i]])-np.min(data[col[i]]))
    transDataDict[col[i]]=temp
transData=pd.DataFrame.from_dict(transDataDict)
del transDataDict

In [6]:
mergeData=transData.apply(lambda x:[x['CHI611'],x['CHI612'],x['CHI621'],x['CHI622'],
x['CHI711'],x['CHI712'],x['CHI721'],x['CHI722'],
x['CHI811'],x['CHI812'],x['CHI821'],x['CHI822'],
x['CHI911'],x['CHI912'],x['CHI921']],axis=1)
mergeData=pd.DataFrame(mergeData,columns=['CHI'])
mergeData['CHINoNan']=mergeData['CHI'].apply(lambda x:[i for i in x if not np.isnan(i)])
mergeData['CHILen']=mergeData['CHINoNan'].apply(lambda x:len(x))

In [7]:
def merge(x,col):
    if col in ['MATH','ENG']:
        x[col]=transData.apply(lambda x:[x[col+'611'],x[col+'612'],x[col+'621'],x[col+'622'],
        x[col+'711'],x[col+'712'],x[col+'721'],x[col+'722'],
        x[col+'811'],x[col+'812'],x[col+'821'],x[col+'822'],
        x[col+'911'],x[col+'912'],x[col+'921']],axis=1)
    elif col == 'PHY':
        x[col]=transData.apply(lambda x:[x[col+'811'],x[col+'812'],x[col+'821'],x[col+'822'],
        x[col+'911'],x[col+'912'],x[col+'921']],axis=1)
    elif col == 'CHE':
        x[col]=transData.apply(lambda x:[x[col+'911'],x[col+'912'],x[col+'921']],axis=1)
def NoNan(x,col):
    x[col+'NoNan']=x[col].apply(lambda x:[i for i in x if not np.isnan(i)])
    x[col+'Len']=x[col+'NoNan'].apply(lambda x:len(x))
def delOrigin(x,col):
    x.drop([col],axis=1,inplace=True)

delOrigin(mergeData,'CHI')

for i in ['MATH','ENG','PHY','CHE']:
    merge(mergeData,i)
    NoNan(mergeData,i)
    delOrigin(mergeData,i)

In [8]:
def normTest(x,col):
    if x[col+'Len']>=3:
        return stats.shapiro(x[col+'NoNan'])
    else:
        return (-1,-1)

for i in ['CHI','MATH','ENG']:
    mergeData[i+'Norm']=mergeData.apply(lambda x:normTest(x,i),axis=1)

In [9]:
def stdTest(df):
    temp=df[['CHINoNan','MATHNoNan','ENGNoNan']].values
    return stats.levene(temp[0],temp[1],temp[2])
mergeData['stdTest']=mergeData.apply(stdTest,axis=1)

In [10]:
equalStdData=mergeData[mergeData['stdTest'].apply(lambda x:x[1]>0.05)].copy()

In [11]:
def oneWay(df):
    temp=df[['CHINoNan','MATHNoNan','ENGNoNan']].values
    return stats.f_oneway(temp[0],temp[1],temp[2])
equalStdData['oneWay']=equalStdData.apply(oneWay,axis=1)

In [12]:
len(equalStdData[equalStdData['oneWay'].apply(lambda x:x[1]>0.05)])

54

In [13]:
equalStdData['isBias']=equalStdData['oneWay'].apply(lambda x:x[1]<0.05)

In [14]:
sexBiasCount=equalStdData.join(data['Sex'])
sexBiasCount=sexBiasCount.groupby(['Sex','isBias'])['CHINoNan'].count().reset_index()
sexBiasCount.rename(columns={'CHINoNan':'count'},inplace=True)
sexBiasCount=sexBiasCount.pivot(index='Sex',columns='isBias',values='count')

In [15]:
sexBiasCount

isBias  False  True 
Sex                 
F          23     64
M          25     71

In [16]:
stats.chi2_contingency(sexBiasCount)

(0.011571704382183943,
 0.9143353224117214,
 1,
 array([[22.81967213, 64.18032787],
        [25.18032787, 70.81967213]]))

In [17]:
for i in ['CHI','MATH','ENG']:
    mergeData[i+'Mean']=mergeData[i+'NoNan'].apply(np.mean)

In [18]:
def findBias(df):
    meanCol=['CHIMean','MATHMean','ENGMean']
    dis=np.zeros(3)
    maxScoreLesson=np.argmax(df[meanCol])
    for i in range(3):
        temp=0
        for j in meanCol:
            temp+=np.abs(df[meanCol[i]]-df[j])
        dis[i]=temp
    argMax=np.argmax(dis)
    flag=(maxScoreLesson==argMax)
    return (np.max(dis),argMax,flag)
mergeData['bias']=mergeData.apply(findBias,axis=1)

In [19]:
mergeData['biasDis']=mergeData['bias'].apply(lambda x:x[0])
mergeData['biasClass']=mergeData['bias'].apply(lambda x:x[1])
mergeData['biasPostive']=mergeData['bias'].apply(lambda x:x[2])

In [20]:
biasData=equalStdData.join(mergeData[['biasDis','biasClass','biasPostive']])[['isBias','biasDis','biasClass','biasPostive']]
biasData=biasData.join(data['Sex'])

In [21]:
classPostiveData=biasData[biasData['isBias']>0].groupby(['biasClass','biasPostive'])['biasDis'].count().reset_index()
temp=classPostiveData.pivot(index='biasPostive',columns='biasClass',values='biasDis')
print(temp)
stats.chi2_contingency(temp)

biasClass     0   1   2
biasPostive            
False        40  19  18
True         19  23  24


(7.913342173027404,
 0.01912667949269471,
 2,
 array([[31.76923077, 22.61538462, 22.61538462],
        [27.23076923, 19.38461538, 19.38461538]]))

In [22]:
#已经偏科的人，偏科的科目和偏科是优势还是劣势不独立
classPostiveData=biasData[biasData['isBias']>0].groupby(['biasClass','biasPostive'])['biasDis'].count().reset_index()
temp=classPostiveData.pivot(index='biasPostive',columns='biasClass',values='biasDis')
print(temp)
stats.chi2_contingency(temp)

biasClass     0   1   2
biasPostive            
False        40  19  18
True         19  23  24


(7.913342173027404,
 0.01912667949269471,
 2,
 array([[31.76923077, 22.61538462, 22.61538462],
        [27.23076923, 19.38461538, 19.38461538]]))

In [23]:
classPostiveData=biasData[biasData['biasPostive']>0].groupby(['isBias','biasClass'])['biasDis'].count().reset_index()
temp=classPostiveData.pivot(index='isBias',columns='biasClass',values='biasDis')
stats.chi2_contingency(temp)

(1.1825275261282586,
 0.5536271888574527,
 2,
 array([[ 8.63829787, 10.12765957,  9.23404255],
        [20.36170213, 23.87234043, 21.76595745]]))

In [24]:
classPostiveData=biasData[.groupby(['isBias','biasClass'])['biasDis'].count().reset_index()
temp=classPostiveData.pivot(index='isBias',columns='biasClass',values='biasDis')
print(temp)
print(stats.chi2_contingency(temp))

SyntaxError: invalid syntax (<ipython-input-24-cb28c9079fde>, line 1)

In [25]:
# 已经偏科的人，偏科科目和性别无关
classPostiveData=biasData[biasData['isBias']>0].groupby(['biasClass','Sex'])['biasDis'].count().reset_index()
temp=classPostiveData.pivot(index='Sex',columns='biasClass',values='biasDis')
print(temp)
stats.chi2_contingency(temp)
classPostiveData=biasData[(biasData['isBias']>0)&(biasData['biasPostive']>0)].groupby(['biasClass','Sex'])['biasDis'].count().reset_index()
temp=classPostiveData.pivot(index='Sex',columns='biasClass',values='biasDis')
print(temp)
stats.chi2_contingency(temp)
classPostiveData=biasData[(biasData['isBias']>0)&(biasData['biasPostive']==0)].groupby(['biasClass','Sex'])['biasDis'].count().reset_index()
temp=classPostiveData.pivot(index='Sex',columns='biasClass',values='biasDis')
print(temp)
stats.chi2_contingency(temp)

biasClass   0   1   2
Sex                  
F          23  17  24
M          33  20  18
biasClass   0   1   2
Sex                  
F          11   8  14
M           7  14  10
biasClass   0  1   2
Sex                 
F          12  9  10
M          26  6   8


(4.918300320694208,
 0.08550758783687076,
 2,
 array([[16.5915493 ,  6.54929577,  7.85915493],
        [21.4084507 ,  8.45070423, 10.14084507]]))

In [26]:
noEqualStdData=mergeData[mergeData['stdTest'].apply(lambda x:x[1]<0.05)].copy()

In [27]:
'''
for i in ['CHI','MATH','ENG']:
    noEqualStdData[i+'Std']=mergeData[i+'NoNan'].apply(np.std)
noEqualStdData[['CHIMean','MATHMean','ENGMean','CHIStd','MATHStd','ENGStd']]
'''

"\nfor i in ['CHI','MATH','ENG']:\n    noEqualStdData[i+'Std']=mergeData[i+'NoNan'].apply(np.std)\nnoEqualStdData[['CHIMean','MATHMean','ENGMean','CHIStd','MATHStd','ENGStd']]\n"

In [28]:
def kruskal(df):
    temp=df[['CHINoNan','MATHNoNan','ENGNoNan']].values
    return stats.kruskal(temp[0],temp[1],temp[2])
noEqualStdData['kruskal']=noEqualStdData.apply(kruskal,axis=1)
noEqualStdData['isBias']=noEqualStdData['kruskal'].apply(lambda x:x[1]<0.05)

In [44]:
isBias=pd.concat([noEqualStdData['isBias'],equalStdData['isBias']],axis=0,ignore_index=True)
data.merge()

0      False
1       True
2       True
3      False
4       True
       ...  
237     True
238     True
239    False
240     True
241     True
Name: isBias, Length: 242, dtype: bool

In [51]:
mergeData[(mergeData['CHILen']<8) | (mergeData['MATHLen']<8) | (mergeData['ENGLen']<8)]

18421052631578946, 0.1342288011695906, 0.08...        4   
171  [-0.1736842105263158, -0.1782711988304094, -0....        4   
182  [-0.18199841395717692, -0.3162878787878788, -0...        6   
183  [0.04736842105263158, 0.06131213450292394, 0.1...        4   
184  [0.1, -0.02202119883040939, 0.0059488692232054...        4   
186  [-0.04736842105263158, -0.1782711988304094, -0...        7   
188  [-0.07894736842105263, -0.02202119883040939, -...        7   
189  [-0.20526315789473684, -0.04285453216374272, 0...        7   
197  [0.08947368421052632, 0.04047880116959061, 0.0...        7   
199  [-0.03684210526315789, -0.16785453216374271, -...        7   
201  [-0.14210526315789473, -0.19910453216374271, -...        7   
205  [-0.3, -0.19910453216374271, -0.13849557522123...        7   
206       [-0.32105263157894737, -0.23035453216374271]        2   
210  [-0.1, -0.19910453216374271, -0.09405113077679...        7   
211  [0.06842105263157895, -0.05327119883040939, -0...        6   
212  [-0.8052631578947368, -0.7824378654970761, -0....        3   
214  [-0.07894736842105263, -0.07410453216374273, -...        4   
215  [-0.015789473684210527, -0.06368786549707606, ...        4   
221  [-0.2578947368421053, -0.42827119883040937, -0...        7   
227  [-0.12105263157894737, -0.07410453216374273, -...        7   
229  [-0.005263157894736842, -0.08452119883040939, ...        4   
234  [-0.19473684210526315, -0.19910453216374271, -...        7   
235  [-0.18421052631578946, -0.15743786549707606, 0...        7   
240  [-0.005263157894736842, -0.10535453216374273, ...        7   

                                              ENGNoNan  ENGLen  \
11   [0.1267056530214424, 0.21802131912058625, 0.17...       4   
35   [-0.0955165692007798, -0.2503331112591606, -0....       4   
75   [0.003248862897985622, -0.03514323784143905, -...       7   
76   [0.10201429499675105, 0.1294137241838774, 0.14...       4   
77   [0.19926905673512005, 0.1935583597987691, 0.08...       3   
82   [0.19841628959276014, 0.19738854895104893, 0.2...       7   
106                                                 []       0   
125  [0.052631578947368335, -0.06045969353764158, 0...       7   
129  [0.13905133203378808, 0.06612258494337107, 0.0...       7   
150  [-0.09570135746606337, -0.029884178321678334, ...       7   
156  [0.06497725795971401, 0.18004663557628248, 0.1...       7   
157  [-0.2189733593242366, -0.17438374417055297, -0...       4   
159  [-0.10786224821312548, -0.07311792138574284, -...       4   
167  [-0.10786224821312548, -0.06045969353764158, 0...       7   
168  [0.015594541910331302, -0.022485009993337784, ...       4   
171  [-0.16959064327485388, -0.22501665556295805, -...       4   
182  [-0.0015837104072398448, 0.04966127622377621, ...       6   
183  [0.003248862897985622, -0.047801465689540315, ...       4   
184  [-0.13255360623781684, -0.14906728847435044, -...       4   
186  [-0.1572449642625082, -0.1364090606262492, -0....       7   
188  [0.003248862897985622, -0.022485009993337784, ...       7   
189  [-0.1572449642625082, -0.22501665556295805, -0...       7   
197  [-0.1572449642625082, -0.11109260493004665, -0...       7   
199  [-0.14489928525016252, -0.1364090606262492, -0...       7   
201  [-0.04613385315139709, 0.015489673550966013, -...       7   
205  [-0.3918128654970761, -0.3389407061958694, -0....       7   
206        [-0.26835607537361933, -0.2503331112591606]       2   
210  [-0.2066276803118909, -0.12375083277814791, -0...       7   
211  [-0.05847953216374277, -0.022485009993337784, ...       7   
212  [-0.7498375568551008, -0.7440039973351099, -0....       3   
214  [-0.04613385315139709, -0.22501665556295805, -...       4   
215  [-0.07082521117608845, -0.09843437708194538, -...       4   
221  [-0.4411955815464588, -0.3515989340439707, -0....       7   
227  [-0.07082521117608845, -0.009826782145236518, ...       7   
229  [-0.1572449642625082, -0.12375083277814791, -0...       4   
234  [-0.03378817413905